networks:
  stage:
    name: stage
    external: true

secrets:
  emqx-rest:
    external: true

services:
  emqx:
    image: ghcr.io/blabtm/emqx:latest
    ports:
      - 1883:1883
      - 18083:18083
      - 20041:20041
    environment:
      EMQX_API_KEY__BOOTSTRAP_FILE: /etc/secret.cfg
    networks:
      - stage
    secrets:
      - source: emqx-rest
        target: /etc/secret.cfg

  emqx-gate-node:
    image: ghcr.io/blabtm/emqx-gate:latest
    environment:
      PORT: 9002
      EMQX_ADAPTER_HOST: emqx
      EMQX_ADAPTER_PORT: 9100
    networks:
      - stage
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr

  emqx-gate:
    image: ghcr.io/blabtm/emqx-gate-proxy:latest
    ports:
      - 9001:9001
    environment:
      NAME: emqx-gate-node
      PORT: 9001
      NODE_PORT: 9002
      NETWORK: 172.28.0.0/16
      EMQX_HOST: emqx
      EMQX_PORT: 18083
      EMQX_ADAPTER_PORT: 9100
      EMQX_USER: gate
      EMQX_PASS: pass
    networks:
      - stage
