networks:
  stage:
    name: stage
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  emqx-data:
    name: emqx-data

services:
  emqx:
    image: ghcr.io/blabtm/emqx:latest
    ports:
      - 1883:1883
      - 18083:18083
      - 20041:20041
    networks:
      - stage
    volumes:
      - emqx-data:/opt/emqx/data
  emqx-gate-node:
    image: ghcr.io/blabtm/emqx-gate:latest
    environment:
      PORT: 9002
      EMQX_ADAPTER_HOST: emqx
      EMQX_ADAPTER_PORT: 9100
    networks:
      - stage
    deploy:
      endpoint_mode: dnsrr
    depends_on:
      - emqx
  emqx-gate:
    image: ghcr.io/blabtm/emqx-gate-proxy:latest
    ports:
      - 9001:9001
    environment:
      NAME: emqx-gate-node
      PORT: 9001
      NODE_PORT: 9002
      NETWORK: 172.28.0.0/16
      EMQX_HOST: emqx
      EMQX_PORT: 18083
      EMQX_ADAPTER_PORT: 9100
      EMQX_USER: bc2a235f2e2cb06b
      EMQX_PASS: zqPqyKfrZWXyFIXdUXYUV6jaaDvbG17EswGKzeYhUaN
    networks:
      - stage
    depends_on:
      - emqx-gate-node
      - emqx
