emqx:
  host: emqx
  port: 18083
  timeout: 5s
psql:
  host: psql
  port: 5432
extd:
  gate:
    name: gate
    port: 9001
    emqx:
      auto:
        enable: false
        timeout: 30s
        adapter:
          port: 9100
