extd:
  port: 9111
  emqx:
    host: emqx
    port: 18083
    retry: 5
    timeout: 15s
  proc:
    emqx:
      adapter:
        port: 9110
      listener:
        port: 20041
  auth:
    pgsql:
      host: pgsql
      port: 5432
