volumes:
  emqx-data:
    name: emqx-data
  emqx-log:
    name: emqx-log

networks:
  nano:
    driver: overlay
    ipam:
      config:
        - subnet: 10.5.0.0/16
  test:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16

services:
  emqx:
    image: ghcr.io/blabtm/emqx:latest
    ports:
      - "9110:9110"
      - "1883:1883"
      - "18083:18083"
      - "20041:20041"
    environment:
      EMQX_NAME: emqx
      EMQX_HOST: emqx
    networks:
      - test
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
    deploy:
      placement:
        constraints: [ node.hostname == earth ]

  extd:
    image: ghcr.io/blabtm/extd:latest
    ports:
      - "9111:80"
    environment:
      EXTD_ADAPTER: emqx:9110
      TZ: Asia/Novosibirsk
    networks:
      - test

