networks:
  mqtt:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  emqx:
    image: ghcr.io/blabtm/emqx:latest
    ports:
      - "9110:9110"
      - "1883:1883"
      - "18083:18083"
      - "20041:20041"
    networks:
      mqtt:
        ipv4_address: 10.5.0.5

  extd:
    image: ghcr.io/blabtm/extd:latest
    ports:
      - "9111:9111"
    environment:
      EXTD_PORT: 9111
      EXTD_PROC_ADAPTER_ADDR: 10.5.0.5:9110
    networks:
      mqtt:
        ipv4_address: 10.5.0.6

