volumes:
  emqx-data:
    name: emqx-data
  emqx-log:
    name: emqx-log

networks:
  nano:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  emqx:
    image: ghcr.io/blabtm/emqx:latest
    ports:
      - "9110:9110"
      - "1883:1883"
      - "18083:18083"
      - "20041:20041"
    environment:
      EMQX_NAME: emqx
      EMQX_HOST: emqx
      EMQX_API_KEY__BOOTSTRAP_FILE: /opt/emqx/data/mnesia/emqx@emqx/security.conf
    networks:
      - nano
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
    deploy:
      placement:
        constraints: [ node.hostname == earth ]

  extd:
    image: ghcr.io/blabtm/extd:latest
    ports:
      - "9111:80"
    environment:
      EXTD_EMQX_ADDR: emqx:18083
      EXTD_USERNAME: extd
      EXTD_PASSWORD: 8b24c3fcd711
      TZ: Asia/Novosibirsk
    networks:
      - nano
    deploy:
      placement:
        constraints: [ node.hostname == pluto ]
