networks:
  emqx:
    driver: bridge

services:
  emqx:
    image: emqx/emqx
    ports:
      - "1883:1883"
      - "18083:18083"
    networks:
      - emqx

  proc:
    image: emqx-lcy-proc
    ports:
      - "9111:9111"
    networks:
      - emqx

